@echo off
echo activate Cloudflare turnel...
cd /d "%~dp0"
echo [1/3] activating backend server...
start "Game Server" cmd /k "uvicorn main:app --host 0.0.0.0 --port 8000"
timeout /t 3 >nul
echo [2/3] establishing connection turnel...
start "Cloudflare Tunnel" cmd /k "cloudflared tunnel --url http://localhost:8000"
echo [3/3] openning browser...
start http://localhost:8000/admin
start http://localhost:8000/
pause